package com.albert.capstoneproject.Data.model

import androidx.room.Entity
import androidx.room.PrimaryKey


/**
 * Data class representing an item in the cart.
 * It is annotated with Room database annotations to be used as an entity in the database.
 *
 * @property id Unique identifier for the cart item. Auto-generates when a new item is inserted.
 * @property productName Name of the product.
 * @property price Price of the product in string format.
 * @property image URL or path to the product image.
 * @property user Email of the user who added the item to the cart.
 * @property count Number of units of the product in the cart.
 * @property selectedColor Color selected for the product.
 * @property selectedSize Size selected for the product.
 */
@Entity(tableName = "cartDatabase")
data class CartItems(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0, // Unique identifier for the cart item. Auto-generated by Room.
    val productName: String = "", // Name of the product.
    var price: String = "", // Price of the product (stored as a string).
    val image: String = "", // URL or path to the product image.
    val user : String = "", // Email of the user who added the item to the cart.
    var count: Int = 0, // Number of units of the product in the cart.
    val selectedColor: String = "", // Color selected for the product.
    val selectedSize: String = "" // Size selected for the product.
)