package com.albert.capstoneproject.Data.model

import androidx.room.Entity
import androidx.room.PrimaryKey


/**
 * Data class representing a favourite product item.
 * It is annotated with Room database annotations to be used as an entity in the database.
 *
 * @property favouriteId Unique identifier for the favourite item. Auto-generates when a new item is inserted.
 * @property productName Name of the favourite product.
 * @property productPrice Price of the favourite product in string format.
 * @property image URL or path to the image of the favourite product.
 * @property user Email of the user who marked the product as a favourite.
 * @property isFav Boolean flag indicating whether the product is a favourite.
 */
@Entity(tableName = "favouritesDatabase")
data class Favourites(
    @PrimaryKey(autoGenerate = true)
    val favouriteId: Long = 0, // Unique identifier for the favourite item. Auto-generated by Room.
    val productName : String, // Name of the favourite product.
    val productPrice : String, // Price of the favourite product (stored as a string).
    val image : String, // URL or path to the product image.
    val user : String = "", // Email of the user who marked the product as a favourite.
    var isFav: Boolean // Boolean flag indicating whether the product is a favourite.
)