package com.albert.capstoneproject.Data.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.time.LocalDateTime


/**
 * Data class representing an order in the system.
 * This class is annotated with Room database annotations to be used as an entity in the database.
 *
 * @property orderId Unique identifier for the order. Auto-generates when a new order is inserted.
 * @property user Email or identifier of the user who placed the order.
 * @property items List of cart items included in the order. Each item contains details like product name, price, and quantity.
 * @property totalPrice Total price of the order calculated from the sum of all item prices.
 * @property orderDate Date and time when the order was placed. Defaults to the current date and time.
 */
@Entity(tableName = "orderDatabase")
data class Order(
    @PrimaryKey(autoGenerate = true)
    val orderId: Long = 0, // Unique identifier for the order. Auto-generated by Room.
    val user: String = "", // Email or identifier of the user who placed the order.
    val items: List<CartItems>, // List of cart items included in the order.
    val totalPrice: Double = 0.0, // Total price of the order.
    val orderDate: LocalDateTime = LocalDateTime.now() // Date and time when the order was placed.
)