package com.albert.capstoneproject.Data.model

import androidx.room.Entity
import androidx.room.PrimaryKey


/**
 * Data class representing personal information of a user.
 * This class is annotated with Room database annotations to be used as an entity in the database.
 *
 * @property infoId Unique identifier for the personal information record. Auto-generates when a new record is inserted.
 * @property user Email or identifier of the user to whom this personal information belongs.
 * @property userName First name of the user.
 * @property userLastName Last name of the user.
 * @property userStreet Street address of the user.
 * @property userCity City where the user resides.
 * @property userHouseNumber House number of the user's address.
 * @property userPostalCode Postal code of the user's address.
 */
@Entity(tableName = "personalDatabase")
data class PersonalInfo(
    @PrimaryKey(autoGenerate = true)
    val infoId: Long = 0, // Unique identifier for the personal information record. Auto-generated by Room.
    val user: String = "", // Email or identifier of the user to whom this personal information belongs.
    val userName: String = "", // First name of the user.
    val userLastName: String = "", // Last name of the user.
    val userStreet: String = "", // Street address of the user.
    val userCity: String =  "", // City where the user resides.
    val userHouseNumber: String = "", // House number of the user's address.
    val userPostalCode: String = "" // Postal code of the user's address.
)
